name: habit_tracker
description: A minimalistic habit tracking application

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  
  # Other utilities
  intl: ^0.20.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Add this line
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true